apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxpod
  name: nginxpod
spec:
  containers:
  - image: himanshuofficial123/k8s-project:1.0
    name: kube-project
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
